name: "JsonAPI CI"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: set -o pipefail && xcodebuild -project "JsonAPI.xcodeproj" -scheme "JsonAPI" -destination "platform=iOS Simulator,OS=13.4,name=iPhone 11 Pro" clean test | xcpretty
